### PR TITLE
switch to dune

### PR DESCRIPTION
**Pull request by redianthus**
Hi,

I switched the project to dune. Note that now, as dune enforces name unification between opam packages name and library names, once you update it there it'll be `tsdl_image` on opam. Once there's a new release I can take care of updating reverse dependencies of the project if you need.

Cheers.

### CODE REVIEW

**Comment by tokenrove** [comment]
Thanks.  Is there a compelling reason to switch to dune?

I see it must enable a few more warnings by default as it caught some dumb bugs (surely `load_tga_rw` should have been exposed, though it's a special case).  I should probably at least update my warning settings more aggressively across all my projects.

**Comment by redianthus** [comment]
A few reasons are listed [here](https://dune.readthedocs.io/en/stable/overview.html).

Also, I find it much more better than other existing tools for many reasons.

Also, it's kinda becoming the standard build system in the OCaml community: I checked (using [this tool](https://git.zapashcanon.fr/zapashcanon/still-dep)) and over the 2387 packages available in opam, 129 are using oasis, 158 are using jbuilder (the previous name of dune) and 814 are using dune. Also, many packages using oasis or jbuilder are now using dune but havn't been updated on opam yet. :)

**Comment by tokenrove** [comment]
Ok.  Do you mind if I think about it over the weekend?  Also, as a consequence, I might make some changes that might obsolete your PR; I hope you don't mind.

I have been resisting seemingly-unnecessary change (in general, not specifically in this package), but perhaps now is the time to go with the flow.  I also have been moving away from language-specific build tools because of all the hassles that occur in multi-language projects, but I suspect the dune-ification of the OCaml ecosystem is inevitable (as similar tools swept over other ecosystems), and if libraries like this are going to be in opam, they might as well behave in the ordinary way even if I don't use build systems like this for my own projects.

Thanks a lot for the contribution and explanation.

**Comment by redianthus** [comment]
> Do you mind if I think about it over the weekend?

Of course no. :)

> as similar tools swept over other ecosystems

Which tools are you referring to ?

**Comment by tokenrove** [comment]
> Which tools are you referring to ?

I'm thinking in particular of my experiences with rebar3 in the Erlang world, which is one of the things that convinced me to go back to generic tools like ninja and a more principled approach to dependencies, vendoring, and so on; that's the situation that's most similar to the dune conversion (existing build tools are bad and unevenly adopted; there are multiple surface syntaxes to support (compare Reason with Elixir); increasing adoption of a packaging system for dependencies), although spending a substantial time with cargo, and much less with stack, also colored my view.

Anyway, these musings are mostly irrelevant to the issue at hand, because my conclusion in the Erlang case was that if one is going to release libraries, there's no point opposing the general trend of the ecosystem, even if one doesn't agree with it.  (And of course, except for the general opposition to change (ecosystems where the tooling changes suffer a lot of bitrot and brittleness because so many of the contributions are from people like myself who aren't consistently active in the community), there's no defending oasis versus dune here; oasis and ocamlbuild are pretty rickety... the same was true of moving to rebar3 from rebar2, even though rebar3 introduced many problems.)

**Comment by tokenrove** [comment]
Closing in favor of #11; let me know if it seems alright to you, and I will take you up on your offer to update any dependencies.  That was remarkably painful, as I expected.  I still have some dependencies of my own to update, too.  Thanks.

**Pull request closed without merging**
