### PR TITLE
keep opam name tsdl-image and keep library name tsdl_image

### PR DESCRIPTION
**Pull request by sanette**
add `name: "tsdl-image"` in opam file to make it upgradable from earlier versions
keep library name tsdl_image to get compatibility with older projects using the library
remove Result
checked with 4.03, 4.08.1 and 4.10

### CODE REVIEW

**Comment by rand00** [comment]
I would love to get this merged, as the dependence on result < 1.5 keeps back important package upgrades for me

**Comment by sanette** [comment]
there seems to be no activity from the maintainer since 2019

**Comment by tokenrove** [comment]
As I've said for years, e.g. https://github.com/tokenrove/tsdl-image/issues/12#issuecomment-675623844, https://github.com/tokenrove/tsdl-image/issues/14#issuecomment-778879842, please go ahead and fork this library if you wish to maintain it.

**Comment by rand00** [comment]
Ok, but that would suggest that the lib in opam should be switched to the forked version instead. I will think about it if I really need the lib again - can make do without it for now

**Comment by sanette** [comment]
> As I've said for years, e.g. [#12 (comment)](https://github.com/tokenrove/tsdl-image/issues/12#issuecomment-675623844), [#14 (comment)](https://github.com/tokenrove/tsdl-image/issues/14#issuecomment-778879842), please go ahead and fork this library if you wish to maintain it.

ok, I'm willing to maintain `tsdl-image/ttf/mixer`
the forks are ready, https://github.com/sanette/tsdl-image, https://github.com/sanette/tsdl-ttf, https://github.com/sanette/tsdl-mixer

if nobody objects, I will submit them to `opam` soon

**Comment by sanette** [comment]
OK, versions 0.3 are now available in `opam`.
WARNING: the new **library name** is now the same as the package name, eg: `tsdl-image`

**Pull request closed without merging**
